pipeline {
    agent {
        docker {
            image 'maven:3.8.1-adoptopenjdk-11'
            args '-u root'
        }
    }
    stages {
        stage('Venafi') {
            steps {
                sh '''#!/bin/bash
                       apt-get update
                       apt-get install --no-install-recommends -y wget ant ca-certificates
                       wget --https-only --secure-protocol=TLSv1_2 https://$CSP_DOMAIN/csc/clients/venafi-csc-latest-x86_64.deb
                       echo "${CSP_CLIENT_SHA256}  venafi-csc-latest-x86_64.deb" | sha256sum -c -
                       wget --https-only --secure-protocol=TLSv1_2 https://$CSP_DOMAIN/poc_guide/venafipkcs11.txt -O /root/venafipkcs11.txt
                       dpkg -i venafi-csc-latest-x86_64.deb
                       set +x
                       /opt/venafi/codesign/bin/pkcs11config getgrant --force --authurl=$CSP_AUTH_URL --hsmurl=$CSP_HSM_URL --username=$CSP_USER --password=$CSP_PASSWORD
                       set -x
                   '''
            }
        }
        stage('Build') { 
            steps {
                sh 'ant clean compile package war sign' 
            }
        }
    }
}